version: '3.8'
services:
  postgres:
    image: postgres:17.6
    container_name: postgresql_security
    restart: always
    environment:
      POSTGRES_DB: security_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5434"