server:
  port: 8081
spring:
  #main:
    #web-application-type: reactive
  application:
    name: gateway-server
  cloud:
    config:
      enabled: true
    gateway:
      routes:
        - id: user-module
          uri: http://localhost:8080
          predicates:
            #- Path: /api/users/**
            - Path=/api/**
