server:
  port: 8081
spring:
  application:
    name: gateway-server
  cloud:
    config:
      enabled: true
    gateway:
      routes:
        - id: user-module
          uri: http://localhost:8080
          predicates:
            - Path=/api/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true