spring:
  application:
    name: notification-module
  mail:
    host: smtp.mail.ru
    port: 465
    username: notification-module@mail.ru
    password:
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true     # SSL вместо STARTTLS
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true




#spring:
#  application:
#    name: notification-module
#  mail:
#    host: live.smtp.mailtrap.io
#    #host: smtp.yandex.ru
#    port: 465
#    username: smtp@mailtrap.io
#    #username: aidar-mautaliev@yandex.ru
#    password: b0b3f049296ec4da2a56793e71187d8b
#    #password: kieoufjzlqypmzyw
#    protocol: smtps
#    properties:
#      mail.smtp:
#        auth: true
#        ssl:
#          enable: true
#        # Добавленные свойства таймаутов (в миллисекундах)
#        connectiontimeout: 10000
#        timeout: 10000
#        writetimeout: 10000









#spring:
#  application:
#    name: notification-module
#  mail:
#    host: smtp.yandex.ru
#    port: 587
#    username: aidar-mautaliev@yandex.ru
#    password: vmcluoenapzhbvuy
#    protocol: smtp
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true    # Required for Yandex
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
#        debug: true
