server:
  port: 8083
spring:
  kafka:
    bootstrap: localhost:9092
  application:
    name: notification-module
  mail:
    host: smtp.mail.ru
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true     # SSL вместо STARTTLS
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true