spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_module_db
    username: postgres
    password: aaadmin
  jpa:
    properties:
      hibernate: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true